#!/usr/bin/env bash

# IFS="#"

echo '"$*" loop'
for arg in "$*"
do
    echo \< $arg \>;
done

echo $'\n"$@" loop'
for arg in "$@"
do
    echo \< $arg \>;
done

echo $'\n$* loop'
for arg in $*
do
    echo \< $arg \>;
done

echo $'\n$@ loop'
for arg in $@;
do
    echo \< $arg \>;
done
